services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      
    networks:
      - app-network

    container_name: lucky-pack-api

    restart: unless-stopped
      
    extra_hosts:
      - "smtp.yandex.ru:77.88.21.158"
      - "smtp.yandex.ru:77.88.21.3"  # Запасной IP

    environment:
      ASPNETCORE_ENVIRONMENT: Production
      EmailOptions__SmtpServer: ${SMTP_SERVER}
      EmailOptions__SmtpPort: ${SMTP_PORT}
      EmailOptions__Email: ${EMAIL}
      EmailOptions__Password: ${EMAIL_PASSWORD}
      EmailOptions__EnableSsl: true
      TelegramOptions__BotToken: ${BOT_TOKEN}
      TelegramOptions__WebAppUrl: ${BOT_WEB_APP_URL}

    ports:
      - "127.0.0.1:8080:8080"
        
networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1