services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      
    networks:
      - app-network

    container_name: lucky-pack-api

    restart: unless-stopped
      
     #заставляют контейнер ходить к Yandex по IPv4, который у вашего сервера не работает.
#    extra_hosts:
#      - "smtp.yandex.ru:77.88.21.158"
#      - "smtp.yandex.ru:77.88.21.3"
        
#    privileged: true
#    sysctls:
#      - net.ipv4.conf.all.forwarding=1
#      - net.ipv4.ip_forward=1

    environment:
      ASPNETCORE_ENVIRONMENT: Production
      EmailOptions__SmtpServer: ${SMTP_SERVER}
      EmailOptions__SmtpPort: ${SMTP_PORT}
      EmailOptions__Email: ${EMAIL}
      EmailOptions__Password: ${EMAIL_PASSWORD}
      EmailOptions__EnableSsl: true
      TelegramOptions__BotToken: ${BOT_TOKEN}
      TelegramOptions__WebAppUrl: ${BOT_WEB_APP_URL}

    ports:
      - "127.0.0.1:8080:8080"
        
networks:
  app-network:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
        - subnet: fd42:20:20::/64